// GENERATED FROM @web3icons/core@4.0.55 — DO NOT EDIT
import SwiftUI

internal struct TokenOBOT: Shape {
    func path(in rect: CGRect) -> Path {
        var path = Path()
        let width = rect.size.width
        let height = rect.size.height
        var _hole2 = Path()
        _hole2.move(to: CGPoint(x: 0.125*width, y: 0.125*height))
        _hole2.addLine(to: CGPoint(x: 0.425*width, y: 0.125*height))
        _hole2.addLine(to: CGPoint(x: 0.425*width, y: 0.25*height))
        _hole2.addLine(to: CGPoint(x: 0.575*width, y: 0.25*height))
        _hole2.addLine(to: CGPoint(x: 0.575*width, y: 0.125*height))
        _hole2.addLine(to: CGPoint(x: 0.875*width, y: 0.125*height))
        _hole2.addLine(to: CGPoint(x: 0.875*width, y: 0.425*height))
        _hole2.addLine(to: CGPoint(x: 0.75*width, y: 0.425*height))
        _hole2.addLine(to: CGPoint(x: 0.75*width, y: 0.575*height))
        _hole2.addLine(to: CGPoint(x: 0.875*width, y: 0.575*height))
        _hole2.addLine(to: CGPoint(x: 0.875*width, y: 0.875*height))
        _hole2.addLine(to: CGPoint(x: 0.575*width, y: 0.875*height))
        _hole2.addLine(to: CGPoint(x: 0.575*width, y: 0.75*height))
        _hole2.addLine(to: CGPoint(x: 0.425*width, y: 0.75*height))
        _hole2.addLine(to: CGPoint(x: 0.425*width, y: 0.875*height))
        _hole2.addLine(to: CGPoint(x: 0.125*width, y: 0.875*height))
        _hole2.addLine(to: CGPoint(x: 0.125*width, y: 0.575*height))
        _hole2.addLine(to: CGPoint(x: 0.25*width, y: 0.575*height))
        _hole2.addLine(to: CGPoint(x: 0.25*width, y: 0.425*height))
        _hole2.addLine(to: CGPoint(x: 0.125*width, y: 0.425*height))
        _hole2.closeSubpath()
        _hole2.move(to: CGPoint(x: 0.425*width, y: 0.425*height))
        _hole2.addLine(to: CGPoint(x: 0.425*width, y: 0.3*height))
        _hole2.addLine(to: CGPoint(x: 0.575*width, y: 0.3*height))
        _hole2.addLine(to: CGPoint(x: 0.575*width, y: 0.425*height))
        _hole2.addLine(to: CGPoint(x: 0.7*width, y: 0.425*height))
        _hole2.addLine(to: CGPoint(x: 0.7*width, y: 0.575*height))
        _hole2.addLine(to: CGPoint(x: 0.575*width, y: 0.575*height))
        _hole2.addLine(to: CGPoint(x: 0.575*width, y: 0.7*height))
        _hole2.addLine(to: CGPoint(x: 0.425*width, y: 0.7*height))
        _hole2.addLine(to: CGPoint(x: 0.425*width, y: 0.575*height))
        _hole2.addLine(to: CGPoint(x: 0.3*width, y: 0.575*height))
        _hole2.addLine(to: CGPoint(x: 0.3*width, y: 0.425*height))
        _hole2.closeSubpath()
        _hole2.move(to: CGPoint(x: 0.2*width, y: 0.35*height))
        _hole2.addLine(to: CGPoint(x: 0.35*width, y: 0.35*height))
        _hole2.addLine(to: CGPoint(x: 0.35*width, y: 0.2*height))
        _hole2.addLine(to: CGPoint(x: 0.2*width, y: 0.2*height))
        _hole2.closeSubpath()
        _hole2.move(to: CGPoint(x: 0.2*width, y: 0.8*height))
        _hole2.addLine(to: CGPoint(x: 0.35*width, y: 0.8*height))
        _hole2.addLine(to: CGPoint(x: 0.35*width, y: 0.65*height))
        _hole2.addLine(to: CGPoint(x: 0.2*width, y: 0.65*height))
        _hole2.closeSubpath()
        _hole2.move(to: CGPoint(x: 0.8*width, y: 0.35*height))
        _hole2.addLine(to: CGPoint(x: 0.65*width, y: 0.35*height))
        _hole2.addLine(to: CGPoint(x: 0.65*width, y: 0.2*height))
        _hole2.addLine(to: CGPoint(x: 0.8*width, y: 0.2*height))
        _hole2.closeSubpath()
        _hole2.move(to: CGPoint(x: 0.65*width, y: 0.8*height))
        _hole2.addLine(to: CGPoint(x: 0.8*width, y: 0.8*height))
        _hole2.addLine(to: CGPoint(x: 0.8*width, y: 0.65*height))
        _hole2.addLine(to: CGPoint(x: 0.65*width, y: 0.65*height))
        _hole2.closeSubpath()
        path.addReversedPath(_hole2)
        return path
    }
}